repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: no-commit-to-branch # Don't allow a commit to master
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.9
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
