name: rla
channels:
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - attrs
  - blas
  - brotli
  - ca-certificates
  - certifi
  - coverage
  - cycler
  - dbus
  - expat
  - fontconfig
  - fonttools
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - iniconfig
  - intel-openmp
  - jpeg
  - kiwisolver
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - more-itertools
  - munkres
  - ncurses
  - numpy
  - numpy-base
  - olefile
  - openjpeg
  - openssl
  - packaging
  - pcre
  - pillow
  - pip
  - pluggy
  - progress
  - py
  - pyparsing
  - pyqt
  - pytest
  - pytest-cov
  - python=3.9
  - python-dateutil
  - qt
  - readline
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - toml
  - tornado
  - tzdata
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - backports-entry-points-selectable
    - cfgv
    - distlib
    - filelock
    - identify
    - nodeenv
    - platformdirs
    - pre-commit
    - pyyaml
    - sumolib
    - traci
    - virtualenv
